name: Deploy AWS Backup System Infrastructure

on:
  push:
    branches:
      - main  # Dispara o workflow em push para a branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Substitua pela sua região AWS

      - name: Deploy CloudFormation Stack
        uses: aws-actions/aws-cloudformation-deploy@v1
        with:
          name: BackupSystemInfrastructure  # Nome da sua stack CloudFormation
          template: backup-infrastructure.yaml  # Caminho para o template
          capabilities: CAPABILITY_NAMED_IAM  # Necessário se o template criar IAM Roles
